project:
  type: website
  output-dir: docs

website:
  title: "Mini-Project #01"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https:// chenbinwu.github.io/STA9750-2025-SPRING/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: spacelab
    toc: false

editor:
  mode: source